[I 2025-03-13 14:36:36.737 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-03-13 14:36:36.742 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2025-03-13 14:36:36.744 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2025-03-13 14:36:36.745 LabApp] 'port_retries' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2025-03-13 14:36:36.747 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-03-13 14:36:36.752 ServerApp] notebook | extension was successfully linked.
[I 2025-03-13 14:36:37.817 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-03-13 14:36:37.896 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-03-13 14:36:37.898 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-03-13 14:36:37.900 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-03-13 14:36:37.927 LabApp] JupyterLab extension loaded from /om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyterlab
[I 2025-03-13 14:36:37.927 LabApp] JupyterLab application directory is /net/vast-storage/scratch/vast/evlab/jackking/anaconda/envs/superurop/share/jupyter/lab
[I 2025-03-13 14:36:37.928 LabApp] Extension Manager is 'pypi'.
[I 2025-03-13 14:36:38.079 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-03-13 14:36:38.086 ServerApp] notebook | extension was successfully loaded.
[I 2025-03-13 14:36:38.086 ServerApp] Serving notebooks from local directory: /net/vast-storage/scratch/vast/evlab/jackking/straightening_dynamics/scripts
[I 2025-03-13 14:36:38.086 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-03-13 14:36:38.086 ServerApp] http://node103:8081/lab?token=a73be677ce387b6ccd234ed866aa0b267d4794f3a07ad263
[I 2025-03-13 14:36:38.087 ServerApp]     http://127.0.0.1:8081/lab?token=a73be677ce387b6ccd234ed866aa0b267d4794f3a07ad263
[I 2025-03-13 14:36:38.087 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-03-13 14:36:38.101 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///rdma/vast-rdma/vast-home/jackking/.local/share/jupyter/runtime/jpserver-2279577-open.html
    Or copy and paste one of these URLs:
        http://node103:8081/lab?token=a73be677ce387b6ccd234ed866aa0b267d4794f3a07ad263
        http://127.0.0.1:8081/lab?token=a73be677ce387b6ccd234ed866aa0b267d4794f3a07ad263
[I 2025-03-13 14:36:38.150 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-03-13 15:42:26.043 ServerApp] 302 GET / (@172.16.24.234) 0.84ms
[I 2025-03-13 15:42:26.048 LabApp] 302 GET /lab? (@172.16.24.234) 0.75ms
[I 2025-03-13 15:42:27.199 ServerApp] 302 GET / (@172.16.24.234) 0.54ms
[I 2025-03-13 15:42:27.202 LabApp] 302 GET /lab? (@172.16.24.234) 0.56ms
[I 2025-03-13 15:42:33.747 ServerApp] 302 GET / (@172.16.24.234) 0.76ms
[I 2025-03-13 15:42:33.751 LabApp] 302 GET /lab? (@172.16.24.234) 0.69ms
[I 2025-03-13 15:42:33.885 ServerApp] Kernel started: e73fbdcf-fc81-4e46-ac2c-463c7f5f05d4
[I 2025-03-13 15:42:35.716 ServerApp] Connecting to kernel e73fbdcf-fc81-4e46-ac2c-463c7f5f05d4.
[I 2025-03-13 15:42:36.627 ServerApp] 302 GET / (@172.16.24.234) 4.57ms
[I 2025-03-13 15:42:36.628 ServerApp] 302 GET / (@172.16.24.234) 0.41ms
[I 2025-03-13 15:42:36.629 ServerApp] 302 GET / (@172.16.24.234) 0.35ms
[I 2025-03-13 15:42:36.630 ServerApp] 302 GET / (@172.16.24.234) 0.31ms
[I 2025-03-13 15:42:36.638 ServerApp] 302 GET / (@172.16.24.234) 0.69ms
[I 2025-03-13 15:42:36.685 LabApp] 302 GET /lab? (@172.16.24.234) 1.97ms
[I 2025-03-13 15:42:36.686 LabApp] 302 GET /lab? (@172.16.24.234) 2.09ms
[I 2025-03-13 15:42:36.686 LabApp] 302 GET /lab? (@172.16.24.234) 2.20ms
[I 2025-03-13 15:42:36.686 LabApp] 302 GET /lab? (@172.16.24.234) 2.33ms
[I 2025-03-13 15:42:36.687 LabApp] 302 GET /lab? (@172.16.24.234) 2.43ms
[W 2025-03-13 15:42:36.731 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.740 ServerApp] 403 GET /api/kernelspecs?1741894956723 (@172.16.24.234) 9.50ms referer=None
[W 2025-03-13 15:42:36.743 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.743 ServerApp] 403 GET /api/kernelspecs?1741894956728 (@172.16.24.234) 2.61ms referer=None
[W 2025-03-13 15:42:36.744 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.744 ServerApp] 403 GET /api/kernelspecs?1741894956730 (@172.16.24.234) 2.76ms referer=None
[W 2025-03-13 15:42:36.744 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.745 ServerApp] 403 GET /api/kernelspecs?1741894956732 (@172.16.24.234) 3.05ms referer=None
[W 2025-03-13 15:42:36.747 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.748 ServerApp] 403 GET /api/kernelspecs?1741894956741 (@172.16.24.234) 0.96ms referer=None
[W 2025-03-13 15:42:36.749 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.749 ServerApp] 403 GET /api/kernels?1741894956724 (@172.16.24.234) 1.08ms referer=None
[W 2025-03-13 15:42:36.750 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.750 ServerApp] 403 GET /api/kernels?1741894956725 (@172.16.24.234) 1.77ms referer=None
[W 2025-03-13 15:42:36.752 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.752 ServerApp] 403 GET /api/sessions?1741894956726 (@172.16.24.234) 1.13ms referer=None
[W 2025-03-13 15:42:36.753 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.753 ServerApp] 403 GET /api/kernels?1741894956729 (@172.16.24.234) 1.55ms referer=None
[W 2025-03-13 15:42:36.754 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.755 ServerApp] 403 GET /api/kernels?1741894956730 (@172.16.24.234) 1.45ms referer=None
[W 2025-03-13 15:42:36.755 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.755 ServerApp] 403 GET /api/kernels?1741894956735 (@172.16.24.234) 1.83ms referer=None
[W 2025-03-13 15:42:36.756 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.756 ServerApp] 403 GET /api/kernels?1741894956736 (@172.16.24.234) 2.20ms referer=None
[W 2025-03-13 15:42:36.756 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.757 ServerApp] 403 GET /api/sessions?1741894956737 (@172.16.24.234) 2.59ms referer=None
[W 2025-03-13 15:42:36.758 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.758 ServerApp] 403 GET /api/kernels?1741894956737 (@172.16.24.234) 1.64ms referer=None
[W 2025-03-13 15:42:36.759 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.759 ServerApp] 403 GET /api/sessions?1741894956738 (@172.16.24.234) 2.00ms referer=None
[W 2025-03-13 15:42:36.759 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.760 ServerApp] 403 GET /api/kernels?1741894956738 (@172.16.24.234) 2.35ms referer=None
[W 2025-03-13 15:42:36.762 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.762 ServerApp] 403 GET /api/sessions?1741894956739 (@172.16.24.234) 1.52ms referer=None
[W 2025-03-13 15:42:36.763 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.763 ServerApp] 403 GET /api/kernels?1741894956741 (@172.16.24.234) 1.86ms referer=None
[W 2025-03-13 15:42:36.763 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.764 ServerApp] 403 GET /api/kernels?1741894956743 (@172.16.24.234) 2.23ms referer=None
[W 2025-03-13 15:42:36.764 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.764 ServerApp] 403 GET /api/sessions?1741894956743 (@172.16.24.234) 2.63ms referer=None
[W 2025-03-13 15:42:36.766 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.767 ServerApp] 403 GET /api/kernelspecs?1741894956744 (@172.16.24.234) 1.45ms referer=None
[W 2025-03-13 15:42:36.767 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.767 ServerApp] 403 GET /api/kernelspecs?1741894956748 (@172.16.24.234) 1.82ms referer=None
[W 2025-03-13 15:42:36.767 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.768 ServerApp] 403 GET /api/kernelspecs?1741894956749 (@172.16.24.234) 2.19ms referer=None
[W 2025-03-13 15:42:36.768 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.768 ServerApp] 403 GET /api/kernelspecs?1741894956749 (@172.16.24.234) 2.57ms referer=None
[W 2025-03-13 15:42:36.769 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.769 ServerApp] 403 GET /api/kernelspecs?1741894956750 (@172.16.24.234) 1.03ms referer=None
[I 2025-03-13 15:42:36.770 ServerApp] 302 GET / (@172.16.24.234) 1.04ms
[I 2025-03-13 15:42:36.771 ServerApp] 302 GET / (@172.16.24.234) 0.28ms
[I 2025-03-13 15:42:36.771 ServerApp] 302 GET / (@172.16.24.234) 0.37ms
[I 2025-03-13 15:42:36.774 ServerApp] 302 GET / (@172.16.24.234) 0.27ms
[I 2025-03-13 15:42:36.778 ServerApp] 302 GET / (@172.16.24.234) 0.31ms
[I 2025-03-13 15:42:36.779 LabApp] 302 GET /lab? (@172.16.24.234) 0.63ms
[I 2025-03-13 15:42:36.780 LabApp] 302 GET /lab? (@172.16.24.234) 0.68ms
[I 2025-03-13 15:42:36.781 LabApp] 302 GET /lab? (@172.16.24.234) 0.75ms
[I 2025-03-13 15:42:36.787 LabApp] 302 GET /lab? (@172.16.24.234) 0.59ms
[I 2025-03-13 15:42:36.789 LabApp] 302 GET /lab? (@172.16.24.234) 0.51ms
[W 2025-03-13 15:42:36.794 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.795 ServerApp] 403 GET /api/kernelspecs?1741894956788 (@172.16.24.234) 0.90ms referer=None
[W 2025-03-13 15:42:36.797 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.798 ServerApp] 403 GET /api/kernelspecs?1741894956791 (@172.16.24.234) 0.85ms referer=None
[W 2025-03-13 15:42:36.798 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.799 ServerApp] 403 GET /api/kernelspecs?1741894956793 (@172.16.24.234) 0.76ms referer=None
[W 2025-03-13 15:42:36.803 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.803 ServerApp] 403 GET /api/kernelspecs?1741894956797 (@172.16.24.234) 1.32ms referer=None
[W 2025-03-13 15:42:36.806 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.806 ServerApp] 403 GET /api/kernels?1741894956788 (@172.16.24.234) 2.25ms referer=None
[W 2025-03-13 15:42:36.807 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.807 ServerApp] 403 GET /api/kernels?1741894956789 (@172.16.24.234) 2.71ms referer=None
[W 2025-03-13 15:42:36.813 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.814 ServerApp] 403 GET /api/kernelspecs?1741894956804 (@172.16.24.234) 4.61ms referer=None
[W 2025-03-13 15:42:36.814 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.815 ServerApp] 403 GET /api/sessions?1741894956790 (@172.16.24.234) 5.32ms referer=None
[W 2025-03-13 15:42:36.815 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.815 ServerApp] 403 GET /api/kernels?1741894956792 (@172.16.24.234) 6.03ms referer=None
[W 2025-03-13 15:42:36.816 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.816 ServerApp] 403 GET /api/kernels?1741894956794 (@172.16.24.234) 6.50ms referer=None
[W 2025-03-13 15:42:36.816 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.817 ServerApp] 403 GET /api/kernels?1741894956794 (@172.16.24.234) 6.87ms referer=None
[W 2025-03-13 15:42:36.817 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.817 ServerApp] 403 GET /api/sessions?1741894956795 (@172.16.24.234) 7.25ms referer=None
[W 2025-03-13 15:42:36.817 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.818 ServerApp] 403 GET /api/kernels?1741894956795 (@172.16.24.234) 7.57ms referer=None
[W 2025-03-13 15:42:36.821 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.821 ServerApp] 403 GET /api/kernelspecs?1741894956802 (@172.16.24.234) 2.25ms referer=None
[W 2025-03-13 15:42:36.821 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.821 ServerApp] 403 GET /api/kernels?1741894956804 (@172.16.24.234) 2.37ms referer=None
[W 2025-03-13 15:42:36.822 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.822 ServerApp] 403 GET /api/kernelspecs?1741894956805 (@172.16.24.234) 2.62ms referer=None
[W 2025-03-13 15:42:36.822 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.823 ServerApp] 403 GET /api/kernels?1741894956806 (@172.16.24.234) 2.83ms referer=None
[W 2025-03-13 15:42:36.824 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.825 ServerApp] 403 GET /api/sessions?1741894956796 (@172.16.24.234) 1.76ms referer=None
[W 2025-03-13 15:42:36.825 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.825 ServerApp] 403 GET /api/kernels?1741894956798 (@172.16.24.234) 2.12ms referer=None
[W 2025-03-13 15:42:36.825 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.826 ServerApp] 403 GET /api/kernels?1741894956800 (@172.16.24.234) 2.51ms referer=None
[W 2025-03-13 15:42:36.826 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.826 ServerApp] 403 GET /api/sessions?1741894956800 (@172.16.24.234) 2.95ms referer=None
[W 2025-03-13 15:42:36.827 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.827 ServerApp] 403 GET /api/kernelspecs?1741894956801 (@172.16.24.234) 3.40ms referer=None
[W 2025-03-13 15:42:36.827 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.828 ServerApp] 403 GET /api/kernelspecs?1741894956802 (@172.16.24.234) 3.84ms referer=None
[W 2025-03-13 15:42:36.829 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.829 ServerApp] 403 GET /api/sessions?1741894956806 (@172.16.24.234) 0.75ms referer=None
[W 2025-03-13 15:42:36.831 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/om2/user/jackking/anaconda/envs/superurop/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-13 15:42:36.832 ServerApp] 403 GET /api/kernelspecs?1741894956813 (@172.16.24.234) 0.66ms referer=None
[W 2025-03-13 15:42:37.142 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.24.234) 13.31ms referer=None
[I 2025-03-13 15:42:37.142 ServerApp] 302 GET / (@172.16.24.234) 13.24ms
[I 2025-03-13 15:42:37.145 LabApp] 302 GET /lab? (@172.16.24.234) 0.62ms
[W 2025-03-13 15:42:37.150 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.24.234) 1.11ms referer=None
[I 2025-03-13 16:41:09.632 ServerApp] Kernel interrupted: e73fbdcf-fc81-4e46-ac2c-463c7f5f05d4
